### ISSUE TITLE
Re packing rsdkvb not working

### ISSUE THREAD

**Issue by enajor66** [Rubberduckycooly/RSDK-Reverse#1]
After decompressing the Data.rsdk.xmf from the latest sonic 2 apk, I modified the file, then pressed "Build data file," switched "save as type" to "RSDKvB Data Files," and typed the name "Data" and "Data.rsdk," but there's no Data.rsdk file in the directory I chose. I chose a different directory than I got the file from. What should I do?

**Comment by Rubberduckycooly** [comment]
Re-packing isn’t done for any RSDK version, I’m gonna be working on that soon

**Comment by Zerodarkfire05** [comment]
Hello, sorry, but it does not work for me, it compresses and then says that it has nothing

**Comment by CarJem** [comment]
Is this still an issue @Rubberduckycooly?

**Comment by Rubberduckycooly** [comment]
Code’s there, it just needs bug testing
